---
- hosts: ios
  tasks: 
    - name: Gather static routes facts
      ios_facts:
        gather_subset:
          - "!all"
          - "!min"
        gather_network_resources:
          - interfaces
