---
- hosts: vyos
  gather_facts: yes
  module_defaults: 
    vyos_facts:
      gather_subset: default
      gather_network_resources:
        - static_routes     
  tasks:
    - name: Delete attributes of given static routes.
      vyos_static_routes:
        config:
        state: deleted


