---
- hosts: vyos
  gather_facts: yes
  module_defaults: 
    vyos_facts:
      gather_subset: default
      gather_network_resources:
        - static_routes     
  tasks:
    - name: Delete attributes of given static routes.
      vyos_static_routes:
        config:
          - address_families:
            - afi: 'ipv4'
              routes:
                - dest: '192.0.0.0/24'      
          - address_families:
            - afi: 'ipv6'      
              routes:
                - dest: '2001:db8::0/32'      
        state: deleted


