---
- hosts: vyos
  gather_facts: yes
  module_defaults: 
    vyos_facts:
      gather_subset: default
      gather_network_resources:
        - static_routes     
  tasks:
    - name: Merge the provided configuration with the exisiting running configuration
      vyos_static_routes: &merged
        config:
         - address_families:
           - afi: 'ipv4'
             routes:
               - dest: 192.0.2.32/28
                 blackhole_config:
                   type: 'blackhole'
                 next_hops:
                   - forward_router_address: 192.0.2.6
                   - forward_router_address: 192.0.2.7
           - afi: 'ipv4'
             routes:
               - dest: 192.0.2.64/28
                 blackhole_config:
                   type: 'blackhole'
                 next_hops:
                   - forward_router_address: 192.0.2.9
                   - forward_router_address: 192.0.2.10
         - address_families:
           - afi: 'ipv6'
             routes:
               - dest: 2001:db8:1000::/36
                 blackhole_config:
                   distance: 2
                 next_hops:
                   - forward_router_address: 2001:db8:2000:2::1
                   - forward_router_address: 2001:db8:2000:2::2  
                         
        state: merged


