---
- hosts: vyos
  gather_facts: yes
  module_defaults: 
    vyos_facts:
      gather_subset: default
      gather_network_resources:
        - static_routes     
  tasks:
    - name: Overrides all device configuration with provided configuration
      vyos_static_routes: &overridden
         config:
           - address_families:
             - afi: 'ipv4'
               routes:
                 - dest: 198.0.2.48/28
                   next_hops:
                     - forward_router_address: 192.0.2.18
         state: overridden
