---
- hosts: vyos
  gather_facts: yes
  module_defaults: 
    vyos_facts:
      gather_subset: default
      gather_network_resources:
        - static_routes     
  tasks:
    - name: Gathere the exisiting running configuration
      vyos_static_routes: &parsed
       running_config: 
         "set protocols static route 192.0.2.32/28 'blackhole'
set protocols static route 192.0.2.32/28 next-hop '192.0.2.6'
set protocols static route 192.0.2.32/28 next-hop '192.0.2.7'
set protocols static route6 2001:db8:1000::/36 blackhole distance '2'
set protocols static route6 2001:db8:1000::/36 next-hop '2001:db8:2000:2::1'
set protocols static route6 2001:db8:1000::/36 next-hop '2001:db8:2000:2::2'"
       state: parsed
