---
- hosts: vyos
  gather_facts: yes
  module_defaults: 
    vyos_facts:
      gather_subset: default
      gather_network_resources:
        - static_routes     
  tasks:
    - name: Parse the provided configuration
      vyos_static_routes: &parsed
       running_config: 
         "set protocols static route 192.0.0.0/24 'blackhole'
set protocols static route 192.0.0.0/24 next-hop '192.11.11.11'
set protocols static route 192.0.0.0/24 next-hop '192.11.11.12'
set protocols static route6 2001:db8::0/32 blackhole distance '2'
set protocols static route6 2001:db8::0/32 next-hop '2001:db8::1'
set protocols static route6 2001:db8::0/32 next-hop '2001:db8::5'"
       state: parsed
