---
- hosts: vyos
  gather_facts: yes
  module_defaults: 
    vyos_facts:
      gather_subset: default
      gather_network_resources:
        - static_routes     
  tasks:
    - name: Replace device configurations of listed static routes with provided configurations
      vyos_static_routes: &replaced
          config:
            - address_families:
              - afi: 'ipv4'
                routes:
                  - dest: 192.0.2.32/28
                    blackhole_config:
                      distance: 2
                    next_hops:
                      - forward_router_address: 192.0.2.7
                        enabled: false
                      - forward_router_address: 192.0.2.9
          state: replaced
      tags:
        - conf
