- hosts: vyos
  gather_facts: false
  connection: network_cli
  collections:
    - vyos.vyos
  tasks:
   - name: ospf_global
     vyos.vyos.vyos_ospf_global: &id001
       config:
         - afi: 'ipv4'
           log_adjacency_changes: 'detail'
           max_metric:
           default_information:
           mpls_te:
           neighbor:
           redistribute:
           parameters:
           passive_interface:
           ospf_area:

       state: deleted
