---
- hosts: asa
  gather_facts: yes
  tasks:
    - name: get v6 addresses
      asa_command:
        commands:
          - show run interface | grep ipv6 address
      register: asa_v6_ips

    - debug:
        var: asa_v6_ips.results
