---
- hosts: vyos
  gather_facts: yes
  module_defaults: 
    vyos_facts:
      gather_subset: default
      gather_network_resources:
        - firewall_rules
  tasks: 
   - name: Merge the provided configuration.
     vyos_firewall_rules: &deletd
       config:
       state: deleted
