---
- hosts: vyos
  gather_facts: yes
  module_defaults: 
    vyos_facts:
      gather_subset: default
      gather_network_resources:
        - firewall_rules
  tasks: 
   - name: Merge the provided configuration.
     vyos_firewall_rules: &merged
       config:
         - afi: 'ipv6'
           rule_sets:
           - name: 'UPLINK'
             description: 'This is ipv6 specific rule-set'
             default_action: 'accept'
         - afi: 'ipv4'
           rule_sets:
             - name: 'INBOUND'
               description: 'IPv4 INBOUND rule set'
               default_action: 'accept'
               rules:
                 - number: 101
                   action: 'accept'
                   description: 'Rule 103 is configured by Ansible'
                   ipsec: 'match-ipsec'
                 - number: 102
                   action: 'reject'
                   description: 'Rule 103 is configured by Ansible'
                   ipsec: 'match-ipsec'
                 - number: 103
                   action: 'accept'
                   description: 'Rule 103 is configured by Ansible'
                   destination:
                     group:
                       address_group: 'inbound'
                   source:
                     address: '192.0.2.0'
                   state:
                     established: true
                     new: false
                     invalid: false
                     related: true

       state: merged              



             
