- hosts: vyos
  gather_facts: false
  connection: network_cli
  collections:
    - vyos.vyos
  tasks:
   - name: ospfv2
     vyos.vyos.vyos_ospfv2: &id001
       config:
         - ospf_area:
             - area: '2'
               area_type:
                 normal: true
               authentication: "plaintext-password"
               shortcut: 'enable'
             - area: '3'
               area_type:
                 nssa:
       state: merged
