---
- hosts: vyos
  gather_facts: yes
  module_defaults: 
    vyos_facts:
      gather_subset: default
      gather_network_resources:
        - firewall_rules
  tasks: 
   - name: Merge the provided configuration.
     vyos_firewall_rules: &overridden
       config:
         - afi: 'ipv6'
           rule_sets:
           - name: 'UPLINK'
             description: 'This is ipv6 specific rule-set'
             default_action: 'accept'
             rules:
               - number: 1
                 action: 'accept'
                 description: 'Fwipv6-Rule 1 is configured by Ansible'
                 ipsec: 'match-ipsec'
               - number: 2
                 action: 'accept'
                 description: 'Fwipv6-Rule 2 is configured by Ansible'
                 ipsec: 'match-ipsec'

         - afi: 'ipv4'
           rule_sets:
             - name: 'INBOUND'
               description: 'IPv4 INBOUND rule set'
               default_action: 'accept'
               rules:
                 - number: 101
                   action: 'accept'
                   description: 'Rule 101 is configured by Ansible'
                   ipsec: 'match-ipsec'
                 - number: 102
                   action: 'reject'
                   description: 'Rule 102 is configured by Ansible'
       state: overridden
